// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190115194201_DbCreateInit")]
    partial class DbCreateInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Domain.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ai");

                    b.Property<int>("Cols");

                    b.Property<int>("GameOver");

                    b.Property<string>("GameShips");

                    b.Property<int>("NumberOfShips");

                    b.Property<string>("PlayerOne")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("PlayerOneBoard");

                    b.Property<int>("PlayerOneTurn");

                    b.Property<string>("PlayerTwo")
                        .HasMaxLength(64);

                    b.Property<string>("PlayerTwoBoard");

                    b.Property<int>("Rows");

                    b.Property<int>("ShipsCanTouch");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
